const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST';
const SET_PLAYLIST = 'SET_PLAYLIST';
const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
const SET_FULL_SCREEN = 'SET_FULL_SCREEN';
const SET_PLAYING_STATE = 'SET_PLAYING_STATE';
const INCREASE_CURRENT_INDEX = 'INCREASE_CURRENT_INDEX';
const DECREASE_CURRENT_INDEX = 'DECREASE_CURRENT_INDEX';
const SET_PLAY_MODE = 'SET_PLAY_MODE';
const ADD_PLAYLIST = 'ADD_PLAYLIST';
const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
const SET_SONG_ID = 'SET_SONG_ID';
const SET_SHOW_PLAY_FLAG = 'SET_SHOW_PLAY_FLAG';

export default {
  SET_SEQUENCE_LIST,
  SET_PLAYLIST,
  SET_CURRENT_INDEX,
  SET_FULL_SCREEN,
  SET_PLAYING_STATE,
  INCREASE_CURRENT_INDEX,
  DECREASE_CURRENT_INDEX,
  SET_PLAY_MODE,
  ADD_PLAYLIST,
  DELETE_PLAYLIST,
  SET_SONG_ID,
  SET_SHOW_PLAY_FLAG
}
